"""Export the trained LightGBM models to C++ headers for the ESP32-S3.

Output: firmware/stage1_model.h and firmware/stage2_model.h
Each header holds a flat node array + one root index per tree.
"""
import joblib

from config import MODELS_DIR, FIRMWARE_DIR, FEATURES


def cpp_float(x):
    """Format a number as a valid C++ float literal (always has '.' or 'e', then 'f').

    '%.9g' prints 0.0 as '0' and 100.0 as '100'; '0f' / '100f' do not compile.
    """
    s = f"{x:.9g}"
    if not any(c in s for c in ".eE"):
        s += ".0"
    return s + "f"


def export_lightgbm_to_header(model, filename, namespace):
    trees = model.booster_.dump_model()["tree_info"]
    nodes, roots = [], []

    def add(node):
        idx = len(nodes)
        nodes.append(None)  # reserve this slot, fill after children are placed

        if "leaf_value" in node:
            nodes[idx] = dict(feature=-1, threshold=0.0, left=-1, right=-1,
                              value=float(node["leaf_value"]),
                              is_leaf=1, default_left=1)
            return idx

        left = add(node["left_child"])
        right = add(node["right_child"])
        nodes[idx] = dict(feature=int(node["split_feature"]),
                          threshold=float(node["threshold"]),
                          left=left, right=right, value=0.0,
                          is_leaf=0,
                          default_left=1 if node.get("default_left", True) else 0)
        return idx

    for tree in trees:
        roots.append(add(tree["tree_structure"]))

    assert len(nodes) < 32768, "Too many nodes for int16_t indices"

    with open(filename, "w") as f:
        f.write("// AUTO-GENERATED by src/export_esp32.py - do not edit by hand\n")
        f.write("// Feature order: " + ", ".join(FEATURES) + "\n\n")
        f.write("#pragma once\n#include <stdint.h>\n\n")
        f.write(f"namespace {namespace} {{\n\n")
        f.write(f"static const int NUM_TREES = {len(trees)};\n")
        f.write(f"static const int NUM_NODES = {len(nodes)};\n\n")
        f.write("struct Node {\n"
                "    int16_t feature;\n    float threshold;\n"
                "    int16_t left;\n    int16_t right;\n    float value;\n"
                "    uint8_t is_leaf;\n    uint8_t default_left;\n};\n\n")
        f.write("static const Node nodes[] PROGMEM = {\n")
        for n in nodes:
            f.write(f"    {{{n['feature']}, {cpp_float(n['threshold'])}, {n['left']}, "
                    f"{n['right']}, {cpp_float(n['value'])}, {n['is_leaf']}, {n['default_left']}}},\n")
        f.write("};\n\n")
        f.write("static const int16_t tree_roots[] PROGMEM = {\n")
        for r in roots:
            f.write(f"    {r},\n")
        f.write("};\n\n}\n")

    print(f"{namespace}: {len(trees)} trees, {len(nodes)} nodes -> {filename}")


def main():
    FIRMWARE_DIR.mkdir(exist_ok=True)
    stage1 = joblib.load(MODELS_DIR / "stage1_model.pkl")
    stage2 = joblib.load(MODELS_DIR / "stage2_model.pkl")
    export_lightgbm_to_header(stage1, FIRMWARE_DIR / "stage1_model.h", "Stage1Model")
    export_lightgbm_to_header(stage2, FIRMWARE_DIR / "stage2_model.h", "Stage2Model")


if __name__ == "__main__":
    main()
